"use client";

import { motion } from "framer-motion";
import { Database, Cpu, Sparkles, Layers, Zap, CheckCircle, Brain, Target, Shield } from "lucide-react";

const pipelineSteps = [
  {
    icon: Database,
    title: "Real Attack Data",
    description: "Curated from penetration testing reports, CVE databases, OWASP benchmarks, and adversarial research.",
    color: "#00d4ff",
    details: ["10K+ real scenarios", "Attack taxonomy mapped", "Diversity validated"],
  },
  {
    icon: Layers,
    title: "Tiered Synthesis",
    description: "Complex scenarios generated by frontier models. Standard scenarios at scale via batch processing.",
    color: "#a855f7",
    details: ["10% frontier quality", "90% scaled generation", "50% cost reduction"],
  },
  {
    icon: Sparkles,
    title: "Multi-Dimensional Mutation",
    description: "Scenario variation, tool-call perturbation, and response diversity to prevent overfitting.",
    color: "#ec4899",
    details: ["Scenario mutation", "Tool-call variation", "Response diversity"],
  },
  {
    icon: CheckCircle,
    title: "Automated Validation",
    description: "Schema validation and quality scoring ensures every sample is deployment-ready.",
    color: "#22c55e",
    details: ["99.4% valid", "Schema enforced", "Quality scored"],
  },
];

const capabilities = [
  { icon: Brain, label: "Deep reasoning", desc: "Multi-step attack planning" },
  { icon: Target, label: "Precision execution", desc: "Tool-call sequencing" },
  { icon: Shield, label: "Evidence verification", desc: "Kernel-level validation" },
];

export default function DatasetPipeline() {
  return (
    <section id="pipeline" className="py-16 sm:py-24 lg:py-32 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-b from-brand-accent/[0.02] via-transparent to-transparent pointer-events-none" />

      <div className="max-w-7xl mx-auto relative z-10">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12 sm:mb-16 lg:mb-20"
        >
          <span className="inline-block px-4 py-1.5 rounded-full bg-brand-accent/10 text-brand-accent text-xs sm:text-sm font-medium mb-4">
            104K+ Training Samples
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 sm:mb-6 text-white">
            Built for
            <span className="text-brand-accent"> Real-World Threats</span>
          </h2>
          <p className="text-sm sm:text-base lg:text-xl text-white/60 max-w-3xl mx-auto leading-relaxed">
            Not synthetic benchmarks. Real attack patterns from production security incidents, refined through continuous feedback loops.
          </p>
        </motion.div>

        {/* Capability icons */}
        <div className="flex flex-wrap items-center justify-center gap-4 sm:gap-6 mb-12 sm:mb-16">
          {capabilities.map((cap, i) => {
            const Icon = cap.icon;
            return (
              <motion.div
                key={cap.label}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="flex items-center gap-2 px-4 py-2 bg-brand-gray/40 border border-white/10 rounded-full"
              >
                <Icon className="w-4 h-4 text-brand-accent" />
                <span className="text-white/70 text-sm">{cap.label}</span>
              </motion.div>
            );
          })}
        </div>

        {/* Pipeline flow */}
        <div className="relative mb-12 sm:mb-16 lg:mb-20">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
            {pipelineSteps.map((step, i) => {
              const Icon = step.icon;
              return (
                <motion.div
                  key={step.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: i * 0.1 }}
                  className="relative"
                >
                  {/* Step number */}
                  <div className="absolute -top-3 left-4 w-6 h-6 rounded-full bg-brand-black border border-white/20 flex items-center justify-center z-10">
                    <span className="text-brand-accent text-xs font-bold">{i + 1}</span>
                  </div>

                  <div className="bg-brand-gray/50 border border-white/10 rounded-2xl p-5 sm:p-6 hover:border-white/20 transition-all duration-300 h-full">
                    <div
                      className="w-12 h-12 rounded-xl flex items-center justify-center mb-4"
                      style={{ backgroundColor: `${step.color}15`, border: `1px solid ${step.color}30` }}
                    >
                      <Icon className="w-6 h-6" style={{ color: step.color }} />
                    </div>

                    <h3 className="text-lg font-bold text-white mb-2">{step.title}</h3>
                    <p className="text-white/50 text-sm leading-relaxed mb-4">{step.description}</p>

                    <div className="flex flex-wrap gap-2">
                      {step.details.map((detail) => (
                        <span
                          key={detail}
                          className="px-2 py-1 rounded-full text-[10px] sm:text-xs font-medium bg-brand-black/40 border border-white/10 text-white/60"
                        >
                          {detail}
                        </span>
                      ))}
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4"
        >
          {[
            { value: "104K+", label: "Training Samples", icon: Database },
            { value: "99.4%", label: "Schema Valid", icon: CheckCircle },
            { value: "50%", label: "Batch Cost Savings", icon: Zap },
            { value: "10", label: "OWASP ASI Coverage", icon: Shield },
          ].map((stat, i) => (
            <div
              key={i}
              className="text-center p-4 sm:p-6 bg-brand-gray/30 border border-white/5 rounded-xl"
            >
              <stat.icon className="w-5 h-5 text-brand-accent mx-auto mb-2" />
              <div className="text-xl sm:text-2xl lg:text-3xl font-bold text-brand-accent mb-1">
                {stat.value}
              </div>
              <div className="text-[10px] sm:text-xs text-white/50">{stat.label}</div>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}